version: '3.8'
services:
    redis:
        image: redislabs/redismod
        ports:
          - "16380:6379"
        volumes:
          - $PWD/data:/data
        command: --dir /data --loadmodule /usr/lib/redis/modules/redistimeseries.so

    app:
        restart: always
        build: .
        ports:
            - "8081:80"
        volumes:
            - $PWD/app:/app
        depends_on:
            - redis
        command: /start-reload.sh
    db:
        image: mysql/mysql-server:8.0.23
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'tribe'
            MYSQL_PASSWORD: 'tr1b3'
            MYSQL_ROOT_PASSWORD: 'secretRoot'
        ports:
            - '3307:3306'
        volumes:
            - $PWD/var/lib/mysql
        expose:
            - 3306